schemas:
  bootstrap: 8000
  sams_map_theme: 8000
favicon:
  mimetype: image/png
  path: 'public://fast.png'
  url: /themes/contrib/bootstrap/favicon.ico
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
table_responsive: '-1'
region_wells:
  header: ''
  primary_menu: ''
  secondary_menu: ''
  featured: ''
  breadcrumb: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
apply: Apply
reset_http_request_cache: ''
table: ''
