_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en-gb
uuid: 28311b7e-c277-421f-91ba-3bde6969be02
name: sams-map
mail: noreply@sams-map.site
slogan: ''
page:
  403: ''
  404: ''
  front: /homepage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
mail_notification: ''
