_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en-gb
uuid: d9669d5f-287f-4f81-8468-895c35d21b8f
name: sams-map
mail: noreply@sams-map.site
slogan: ''
page:
  403: ''
  404: ''
  front: /homepage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
mail_notification: ''
